### ISSUE TITLE
Render distance of 8 chunks crashes the client on world load

### ISSUE THREAD

**Issue by ojbr** [JungleTree/JungleTree#31]
When I set my client's render distance to 8 chunks, and attempt to login to the demo server, the client crashes back to the homescreen.

Affects Windows 10, Android, iOS

**Comment by MarfGamer** [comment]
My solution for now would to be kicking the player with something like "Invalid render distance (8), please change your render distance." As a way to prevent unexplainable crashes for players until it is fixed.

**Comment by ojbr** [comment]
The demo server is not particularly important. If we really wanted to, we could force the client to change their render distance by sending a ChunkRadiusUpdatedPacket

**Comment by ojbr** [comment]
Client was rejecting chunks that were outside of the current render distance, as expected. The fix was to the algorithm which requests chunks from the world service
